baseURL = "https://bkbooth.me/"
languageCode = "en-AU"
title = "Ben Booth"
paginate = 5
Copyright = "Ben Booth © 2017"
canonifyurls = true

[params]
  description = "Some thoughts and ramblings of Ben Booth. I'm a software developer specialising in JavaScript as well as a husband & father, football (soccer) addict and a Christian."
  # metadescription = "Used as 'description' meta tag for both home and index pages. If not set, 'description' will be used instead"
  # cover = "images/cover.jpg"
  author = "Ben Booth"
  authorlocation = "Wollongong, Australia"
  authorwebsite = "https://about.me/bkbooth"
  bio= "Software developer specialising in JavaScript, husband & father, football (soccer) addict and Christian."
  # logo = "images/logo.png"
  googleAnalyticsUserID = "UA-46740857-2"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  # RSSLink = "http://feeds.feedburner.com/..."
  githubName = "bkbooth"
  twitterName = "bkbooth11"
  # facebookName = ""
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = true

  # Setting a value will load highlight.js and enable syntax highlighting using the style selected.
  # See https://github.com/isagalaev/highlight.js/tree/master/src/styles for available styles
  # A preview of above styles can be viewed at https://highlightjs.org/static/demo/
  hjsStyle = "default"

  [params.social]
    twitter = "bkbooth11"
